### ISSUE TITLE
如何添加扩展？比如swoole

### ISSUE THREAD

**Issue by skystian** [xpf0000/BuildPhp#5]
展示的扩展太少了，如何添加扩展？比如swoole

**Comment by xpf0000** [comment]
1. 这边会收集反馈, 添加到一键安装里
2. 未添加到一键安装里的 使用如下方法安装 替换成自己的PHP版本
cd 扩展目录
/usr/local/Cellar/php@7.2.34/7.2.34/bin/phpize
./configure --with-php-config=/usr/local/Cellar/php@7.2.34/7.2.34/bin/php-config
make
make install
