### ISSUE TITLE
安装/切换php出现错误..以及安装redis出现错误

### ISSUE THREAD

**Issue by ypf138199209** [xpf0000/BuildPhp#6]
![image](https://user-images.githubusercontent.com/20056143/113974697-ef17b700-9870-11eb-9460-6884472c8b71.png)
![image](https://user-images.githubusercontent.com/20056143/113974730-fd65d300-9870-11eb-98b8-e04fe1e4de9f.png)
电脑是M1芯片,homebrew安装在/opt/homebrew/,这个大佬您没有去识别

**Comment by xpf0000** [comment]
redis这个已修复 可以再试下
php安装报错这个 你的brew软件安装位置是不是不是默认的? 是全都报错? 还是个别版本报错?

**Comment by ypf138199209** [comment]
php所有版本都无法安装无法切换。
而且我是mac m1芯片。官方的brew都默认安装到/opt/homebrew/
我自己用zsh安装了brew以及各种环境，能正常使用。
不过大佬你很厉害哦！
m1芯片有很多特性。最大的特性就是/usr即使关了SIP保护机制也无法更改/usr的权限和进行任何更改

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月12日(周一) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xpf0000/BuildPhp] 安装/切换php出现错误..以及安装redis出现错误 (#6)




 
redis这个已修复 可以再试下
 php安装报错这个 你的brew软件安装位置是不是不是默认的? 是全都报错? 还是个别版本报错?

**Comment by ypf138199209** [comment]
我用官方的最新的brew默认安装是在/opt/homebrew的
而大佬的还是在/usr/local
官方的最新的brew好像是识别了m1芯片



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月12日(周一) 晚上7:40
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xpf0000/BuildPhp] 安装/切换php出现错误..以及安装redis出现错误 (#6)




 
redis这个已修复 可以再试下
 php安装报错这个 你的brew软件安装位置是不是不是默认的? 是全都报错? 还是个别版本报错?

**Comment by ypf138199209** [comment]
我说下我的过程吧,方便大佬找到问题以及后面用buildPhp的能找到问题.
1.我macbook是"m1"芯片,是有SIP完整性保护机制,即使关闭SIP还是无法"更删改"/usr里面的内容的
2.官方最新的homebrew是适配了m1芯片的,看他源码是如果识别是m1芯片(ARM),就默认安装在/opt/homebrew
过程:
1.我先官网安装了最新的homebrew默认在/opt/homebrew,然后使用buildphp安装环境,安装中一直检测到我没有安装homebrew,就开始在/usr/local安装homebrew了,系统就存在2个homebrew了
2.然后我想安装php环境,选择了7.2.34版本,发现安装在启动/切换过程中失败了,错误就是上面的图.
3.我以为是php版本导致的某些问题,就切换各种php版本来安装,也都失败了.说是找不到icu4c
4.然后我就找到文件中的icu4c发现icu版本是***版本的(忘记了,反正比教高),然后我就把icu的版本降下来,发现还是抱同样的错误.
5.我又猜想是不是因为我安装了2个homebrew的原因,我就把官网和buildphp的homebrew彻底删除,然后直接用buildphp再次安装homebrew,还是同样的错误.

**Comment by xpf0000** [comment]
原来的brew安装程序没有支持到M1 最新版本的已经支持了 
brew的安装位置是有检测的 调用的就是brew自带的命令
brew --repo  检测brew安装位置
brew --cellar  检测cellar文件夹位置
可以升级到最新版再试下

**Comment by ypf138199209** [comment]
好的，厉害大佬。谢谢。辛苦大佬了。希望buildphp越来越好，越来越多人使用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年4月15日(周四) 晚上8:21
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [xpf0000/BuildPhp] 安装/切换php出现错误..以及安装redis出现错误 (#6)




 
原来的brew安装程序没有支持到M1 最新版本的已经支持了
 brew的安装位置是有检测的 调用的就是brew自带的命令
 brew --repo  检测brew安装位置
 brew --cellar  检测cellar文件夹位置
 可以升级到最新版再试下
