### ISSUE TITLE
密码错误，请重新输入

### ISSUE THREAD

**Issue by MrQiYin** [xpf0000/BuildPhp#7]
大佬，我刚下载了Mac版的，然后在打开软件后第一步，【请输入电脑用户密码】，输入密码后显示【密码错误，请重新输入】

**Comment by xpf0000** [comment]
在终端中执行如下命令

**Comment by MrQiYin** [comment]
> 在终端中执行如下命令 echo "电脑用户密码" | sudo -S -v
> 如果能正常执行 不需要输入密码 说明你的密码确实输入的不对
> 如果还是提示需要输入密码 请提供mac系统版本

我刚试了下，不行，命令输入完，从按回车开始，显示结果如下：

`
Password:
【两三秒之后】
Password:**jkl;'**Sorry, try again.
Password:
sudo: no password was provided
sudo: 1 incorrect password attempt
`

macOS Big Sur
版本：11.2.3 (20D91)

**Comment by MrQiYin** [comment]
> 在终端中执行如下命令 echo "电脑用户密码" | sudo -S -v
> 如果能正常执行 不需要输入密码 说明你的密码确实输入的不对
> 如果还是提示需要输入密码 请提供mac系统版本

我又测试了几次，这个两三秒是固定的，即便我什么都不输入，它还是按照这个流程走，而且无论输入什么，这个两三秒之后的流程是一瞬间一起出现的

**Comment by MrQiYin** [comment]
刚又测试了下，应该是我的密码设置的问题，旧密码是【jkl;'】，改成【asdf】就好了。。
